DROP TABLE IF EXISTS TAB_SUBSCRIBER ;

CREATE TABLE IF NOT EXISTS TAB_SUBSCRIBER (
    ID_SUBSCRIBER int(11) NOT NULL auto_increment,
    SUBSCRIBER_NOM varchar(200) NOT NULL DEFAULT '',
    SUBSCRIBER_EXPIRATION timestamp NOT NULL DEFAULT 0,
    SUBSCRIBER_TOKEN varchar(200) NOT NULL DEFAULT '',
    SUBSCRIBER_DATEINSCRIPTION datetime NOT NULL,
    id_client varchar(200) NOT NULL DEFAULT '',
    PRIMARY KEY (ID_SUBSCRIBER)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE INDEX SUBSCRIBER_TOKEN ON TAB_SUBSCRIBER (SUBSCRIBER_TOKEN ASC);
CREATE INDEX id_client ON TAB_SUBSCRIBER (id_client ASC);
